/**
 * Notification type definitions, severity mappings, and constants.
 * Central registry for all notification types in the system.
 */

export type NotificationSeverity = "CRITICAL" | "IMPORTANT" | "UPDATE";
export type NotificationFamily = "ACCOUNT" | "MARKET" | "CLAN" | "SYSTEM";

// ---- Notification type registry ----

export const NOTIFICATION_TYPES = {
  // Account / Tracking
  TRACKING_LOST: "tracking_lost",
  TRACKING_RESTORED: "tracking_restored",
  TRACKING_PROVISIONAL: "tracking_provisional",

  // Trade actions
  TRADE_CLOSED: "trade_closed",
  TRADE_ACTION_SUCCESS: "trade_action_success",
  TRADE_ACTION_FAILED: "trade_action_failed",

  // Risk warnings
  RISK_NO_SL: "risk_no_sl",
  RISK_DRAWDOWN: "risk_drawdown",

  // Integrity / qualification
  INTEGRITY_LOST: "integrity_lost",
  QUALIFICATION_MISSED: "qualification_missed",

  // Market
  PRICE_ALERT_TRIGGERED: "price_alert_triggered",
  PRICE_ALERT_EXPIRED: "price_alert_expired",
  EVENT_REMINDER: "event_reminder",

  // Clan
  RANK_CHANGE: "rank_change",
  CLAN_JOIN_REQUEST: "clan_join_request",
  CLAN_MEMBER_JOINED: "clan_member_joined",
  CLAN_JOIN_APPROVED: "clan_join_approved",
  CLAN_JOIN_REJECTED: "clan_join_rejected",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

// ---- Severity mapping ----

export const SEVERITY_MAP: Record<NotificationType, NotificationSeverity> = {
  // Critical
  [NOTIFICATION_TYPES.TRACKING_LOST]: "IMPORTANT",
  [NOTIFICATION_TYPES.TRADE_ACTION_FAILED]: "CRITICAL",
  [NOTIFICATION_TYPES.RISK_DRAWDOWN]: "CRITICAL",
  [NOTIFICATION_TYPES.RISK_NO_SL]: "CRITICAL",

  // Important
  [NOTIFICATION_TYPES.TRACKING_RESTORED]: "IMPORTANT",
  [NOTIFICATION_TYPES.TRACKING_PROVISIONAL]: "IMPORTANT",
  [NOTIFICATION_TYPES.INTEGRITY_LOST]: "IMPORTANT",
  [NOTIFICATION_TYPES.QUALIFICATION_MISSED]: "IMPORTANT",
  [NOTIFICATION_TYPES.PRICE_ALERT_TRIGGERED]: "IMPORTANT",
  [NOTIFICATION_TYPES.PRICE_ALERT_EXPIRED]: "UPDATE",
  [NOTIFICATION_TYPES.RANK_CHANGE]: "IMPORTANT",
  [NOTIFICATION_TYPES.EVENT_REMINDER]: "IMPORTANT",
  [NOTIFICATION_TYPES.CLAN_JOIN_REQUEST]: "IMPORTANT",
  [NOTIFICATION_TYPES.CLAN_JOIN_APPROVED]: "IMPORTANT",
  [NOTIFICATION_TYPES.CLAN_JOIN_REJECTED]: "IMPORTANT",

  // Updates
  [NOTIFICATION_TYPES.TRADE_CLOSED]: "UPDATE",
  [NOTIFICATION_TYPES.TRADE_ACTION_SUCCESS]: "UPDATE",
  [NOTIFICATION_TYPES.CLAN_MEMBER_JOINED]: "UPDATE",
};

// ---- Family mapping ----

export const FAMILY_MAP: Record<NotificationType, NotificationFamily> = {
  [NOTIFICATION_TYPES.TRACKING_LOST]: "ACCOUNT",
  [NOTIFICATION_TYPES.TRACKING_RESTORED]: "ACCOUNT",
  [NOTIFICATION_TYPES.TRACKING_PROVISIONAL]: "ACCOUNT",
  [NOTIFICATION_TYPES.TRADE_CLOSED]: "ACCOUNT",
  [NOTIFICATION_TYPES.TRADE_ACTION_SUCCESS]: "ACCOUNT",
  [NOTIFICATION_TYPES.TRADE_ACTION_FAILED]: "ACCOUNT",
  [NOTIFICATION_TYPES.RISK_NO_SL]: "ACCOUNT",
  [NOTIFICATION_TYPES.RISK_DRAWDOWN]: "ACCOUNT",
  [NOTIFICATION_TYPES.INTEGRITY_LOST]: "ACCOUNT",
  [NOTIFICATION_TYPES.QUALIFICATION_MISSED]: "ACCOUNT",
  [NOTIFICATION_TYPES.PRICE_ALERT_TRIGGERED]: "MARKET",
  [NOTIFICATION_TYPES.PRICE_ALERT_EXPIRED]: "MARKET",
  [NOTIFICATION_TYPES.EVENT_REMINDER]: "MARKET",
  [NOTIFICATION_TYPES.RANK_CHANGE]: "CLAN",
  [NOTIFICATION_TYPES.CLAN_JOIN_REQUEST]: "CLAN",
  [NOTIFICATION_TYPES.CLAN_MEMBER_JOINED]: "CLAN",
  [NOTIFICATION_TYPES.CLAN_JOIN_APPROVED]: "CLAN",
  [NOTIFICATION_TYPES.CLAN_JOIN_REJECTED]: "CLAN",
};

// ---- Cooldown windows (seconds) for noisy event types ----

export const COOLDOWN_SECONDS: Partial<Record<NotificationType, number>> = {
  [NOTIFICATION_TYPES.TRACKING_LOST]: 3600, // 1 hour
  [NOTIFICATION_TYPES.TRACKING_RESTORED]: 3600,
  [NOTIFICATION_TYPES.TRACKING_PROVISIONAL]: 3600,
  [NOTIFICATION_TYPES.RISK_NO_SL]: 3600, // 1 hour
  [NOTIFICATION_TYPES.RISK_DRAWDOWN]: 1800, // 30 min
  [NOTIFICATION_TYPES.RANK_CHANGE]: 3600, // 1 hour
};

// ---- Push categories (user-facing groupings for push preferences) ----

export const PUSH_CATEGORIES = {
  TRADES: "trades",
  PRICE_ALERTS: "price_alerts",
  RISK: "risk",
  TRACKING: "tracking",
  INTEGRITY: "integrity",
  CLAN: "clan",
} as const;

export type PushCategory = (typeof PUSH_CATEGORIES)[keyof typeof PUSH_CATEGORIES];

/** Maps each notification type to its push category */
export const PUSH_CATEGORY_MAP: Record<NotificationType, PushCategory> = {
  [NOTIFICATION_TYPES.TRADE_CLOSED]: PUSH_CATEGORIES.TRADES,
  [NOTIFICATION_TYPES.TRADE_ACTION_SUCCESS]: PUSH_CATEGORIES.TRADES,
  [NOTIFICATION_TYPES.TRADE_ACTION_FAILED]: PUSH_CATEGORIES.TRADES,
  [NOTIFICATION_TYPES.PRICE_ALERT_TRIGGERED]: PUSH_CATEGORIES.PRICE_ALERTS,
  [NOTIFICATION_TYPES.PRICE_ALERT_EXPIRED]: PUSH_CATEGORIES.PRICE_ALERTS,
  [NOTIFICATION_TYPES.EVENT_REMINDER]: PUSH_CATEGORIES.PRICE_ALERTS,
  [NOTIFICATION_TYPES.RISK_NO_SL]: PUSH_CATEGORIES.RISK,
  [NOTIFICATION_TYPES.RISK_DRAWDOWN]: PUSH_CATEGORIES.RISK,
  [NOTIFICATION_TYPES.TRACKING_LOST]: PUSH_CATEGORIES.TRACKING,
  [NOTIFICATION_TYPES.TRACKING_RESTORED]: PUSH_CATEGORIES.TRACKING,
  [NOTIFICATION_TYPES.TRACKING_PROVISIONAL]: PUSH_CATEGORIES.TRACKING,
  [NOTIFICATION_TYPES.INTEGRITY_LOST]: PUSH_CATEGORIES.INTEGRITY,
  [NOTIFICATION_TYPES.QUALIFICATION_MISSED]: PUSH_CATEGORIES.INTEGRITY,
  [NOTIFICATION_TYPES.RANK_CHANGE]: PUSH_CATEGORIES.CLAN,
  [NOTIFICATION_TYPES.CLAN_JOIN_REQUEST]: PUSH_CATEGORIES.CLAN,
  [NOTIFICATION_TYPES.CLAN_MEMBER_JOINED]: PUSH_CATEGORIES.CLAN,
  [NOTIFICATION_TYPES.CLAN_JOIN_APPROVED]: PUSH_CATEGORIES.CLAN,
  [NOTIFICATION_TYPES.CLAN_JOIN_REJECTED]: PUSH_CATEGORIES.CLAN,
};

/** All categories enabled by default */
export const DEFAULT_PUSH_CATEGORIES: Record<PushCategory, boolean> = {
  [PUSH_CATEGORIES.TRADES]: true,
  [PUSH_CATEGORIES.PRICE_ALERTS]: true,
  [PUSH_CATEGORIES.RISK]: true,
  [PUSH_CATEGORIES.TRACKING]: true,
  [PUSH_CATEGORIES.INTEGRITY]: true,
  [PUSH_CATEGORIES.CLAN]: true,
};

/** Ordered list for UI display */
export const PUSH_CATEGORY_ORDER: PushCategory[] = [
  PUSH_CATEGORIES.TRADES,
  PUSH_CATEGORIES.PRICE_ALERTS,
  PUSH_CATEGORIES.RISK,
  PUSH_CATEGORIES.TRACKING,
  PUSH_CATEGORIES.INTEGRITY,
  PUSH_CATEGORIES.CLAN,
];

// ---- Constants ----

export const MAX_PRICE_ALERTS_PER_USER = 50;
export const PRICE_ALERT_EXPIRY_DAYS = 30;
export const NOTIFICATIONS_PER_PAGE = 20;
export const DROPDOWN_NOTIFICATION_COUNT = 8;
export const MAX_UNREAD_DISPLAY = 99;
